Tạo một vector có các giá trị như sau: 26, 7, 19, 27, 12, 29.
Sử dụng lệnh để cho biết số chiều và số phần tử của vector vừa tạo?

In [11]:
import numpy as np

arr1 = np.array([26,7,19,27,12,29])
print(arr)
print(type(arr))

[26  7 19 27 12 29]
<class 'numpy.ndarray'>


Tạo một vector gồm 15 phần tử với các giá trị ngẫu nhiên từ 1-9?
Cho biết giá trị của phần tử thứ 5 trong vector vừa tạo?

In [10]:
arr2 = np.random.randint(1,9,size = 15)
print(arr2)
print(arr2[5])

[6 1 7 6 1 6 3 3 5 8 5 5 1 7 4]
6


Tạo một ma trận có kích thước 3x4, với các giá trị ngẫu nhiên.
Cho biết chiều và số dòng, số cột của ma trận này?

In [15]:
arr3 = np.random.randint(1,9,size = (3,4))
print(arr3)
print(np.size(arr3))
print(np.size(arr3,0))
print(np.size(arr3,1))

[[5 7 8 2]
 [7 8 6 5]
 [6 4 5 1]]
12
3
4


Tạo một mảng có số dòng, số cột và các giá trị như sau:
- Cho biết số chiều, số dòng, số cột của mảng trên.
- Lấy tất cả giá trị của dòng 2 và dòng 3.
- Tạo một vector với các giá trị được lấy từ cột thứ 3.
- Tạo ra một ma trận mới với các giá trị được lấy từ ma trận trên
- Thay đổi giá trị 22 ở dòng 4, cột 2 thành giá trị 30.

In [77]:
arr4 =np.array([[5,10,21],[11,23,18],[22,19,35],[96,22,26]])
print("Lay dong 2 va 3 ",arr4[1:3])
print(arr4[1:,1:])
arr4[3,1]=30
print(arr4)

Lay dong 2 va 3  [[11 23 18]
 [22 19 35]]
[[23 18]
 [19 35]
 [22 26]]
[[ 5 10 21]
 [11 23 18]
 [22 19 35]
 [96 30 26]]


Tạo mảng 1 chiều với các giá trị từ 10 đến 20?

In [69]:
arr5 =  np.random.randint(10,20,size = 10)
print(arr5)
a2D= arr5.reshape(2,5)
print(a2D)
print(a2D.ndim)

[15 16 12 16 19 15 16 17 16 11]
[[15 16 12 16 19]
 [15 16 17 16 11]]
2


Tạo mảng 1 chiều với các giá trị như sau: 99, 46, 87, 62, 11, 32.
- Cho biết giá trị lớn nhất và nhỏ nhất của mảng trên?
- Sắp xếp mảng này theo tứ tự tăng dần?
- In ra các giá trị ở vị trí chẵn của mảng.
- Kiểm tra phần tử thứ 4 là giá trị chẵn hay lẻ. Xuất thông báo kết quả?
- Đếm số phần tử chẳn có trong mảng.
- Tìm giá trị trung bình (mean), giá trị trung vị (median), tổng?
- Thay đổi giá trị 87 bằng giá trị trung bình của mảng này?
- Xóa phần tử có giá trị 62 trong mảng?

In [84]:
arr6 = np.array([99,46,87,62,11,32])
print(np.max(arr6))
print(np.min(arr6))
arr6 = np.sort(arr6)
print(arr6)

print(np.sum(arr6 % 2 == 0))
mean_val = arr6.mean()
median_val = np.median(arr6)
sum_val = arr6.sum()
print("Giá trị trung bình (mean):", mean_val)
print("Giá trị trung vị (median):", median_val)
print("Tổng:", sum_val)


arr6[arr6 == 87] = mean_val
print("Mảng sau khi thay 87 bằng giá trị trung bình:", arr6)


arr6 = arr6[arr != 62]
print("Mảng sau khi xóa phần tử 62:", arr)

99
11
[11 32 46 62 87 99]
3
Giá trị trung bình (mean): 20.0
Giá trị trung vị (median): 22.5
Tổng: 120
Mảng sau khi thay 87 bằng giá trị trung bình: [11 32 46 62 20 99]
Mảng sau khi xóa phần tử 62: [26  7 19 27 12 29]


In [85]:
matrix1 = np.array([[5, 10, 21],
                    [11, 23, 18],
                    [22, 19, 35]])

matrix2 = np.array([[50, 10, 40],
                    [61, 23, 28],
                    [42, 11, 25]])

matrix3 = np.array([[96, 22, 26],
                    [87, 56, 23],
                    [90, 75, 32]])
print("Hàng từ 1 trở đi của matrix1:\n", matrix1[1:,])

mean_val = matrix1.mean()
print("Giá trị trung bình của matrix1:", mean_val)

matrix2[:, 0] = mean_val
print("matrix2 sau khi thay cột đầu tiên:\n", matrix2)

sum_matrix3 = matrix3.sum()
print("Tổng giá trị của matrix3:", sum_matrix3)

matrix3[-1, :] = -1
print("matrix3 sau khi thay dòng cuối cùng:\n", matrix3)


new_matrix = np.copy(matrix2)
print("Chiều của ma trận mới:", new_matrix.shape)


vector = new_matrix.flatten()
vector = np.append(vector, 45)
print("Vector sau khi thêm 45:", vector)

vector = np.insert(vector, 0, 99)
print("Vector sau khi thêm 99 vào đầu:", vector)

list_from_matrix3 = matrix3.flatten().tolist()
print("List từ matrix3:", list_from_matrix3)


Hàng từ 1 trở đi của matrix1:
 [[11 23 18]
 [22 19 35]]
Giá trị trung bình của matrix1: 18.22222222222222
matrix2 sau khi thay cột đầu tiên:
 [[18 10 40]
 [18 23 28]
 [18 11 25]]
Tổng giá trị của matrix3: 507
matrix3 sau khi thay dòng cuối cùng:
 [[96 22 26]
 [87 56 23]
 [-1 -1 -1]]
Chiều của ma trận mới: (3, 3)
Vector sau khi thêm 45: [18 10 40 18 23 28 18 11 25 45]
Vector sau khi thêm 99 vào đầu: [99 18 10 40 18 23 28 18 11 25 45]
List từ matrix3: [96, 22, 26, 87, 56, 23, -1, -1, -1]


Cho một list như sau: ds = [15, 32, 10, 32, 29, 48, 21]
- Tạo một vector từ danh sách trên.
- Cho biết số phần tử và số chiều của vector.
- Chuyển vector vừa tạo thành ma trận với kích thước 2x4?
- Thêm phần tử có giá trị 55 vào vị trí thứ 2 của vector. Sau đó chuyển vector trên
thành ma trận với kích thước 4x2?
- Xuất ra giá trị của phần tử ở vị trí lẻ?

In [8]:
ds = np.array([15,32,10,32,29,48,21])

vec = ds.flatten()
print(vec.size)
print(vec.ndim)
matrix = vec[:6].reshape(2,3)
print(matrix)

7
1
[[15 32 10]
 [32 29 48]]


In [10]:
import pandas as pd
df = pd.read_csv("sinhvien.csv", encoding="utf-8")
matrix = df.to_numpy()
print(matrix)


[['16050007;Đặng Phương Anh;24/02/1998;F;7;QH-2016-E KTPT']
 ['16051722;Đinh Thị Vân Anh;21/11/1998;F;9;QH-2017-E KINH TẾ']
 ['16050014;Đỗ Lan Anh;;F;4;QH-2017-E KTPT']
 ['16051723;Kiều Ngọc Ánh;06/10/1998;F;6;QH-2017-E KTPT']
 ['16050008;Lê Ngọc Ánh;17/02/1998;F;3;QH-2017-E KTPT']
 ['16052308;Vũ Thị Ánh;12/07/1998;F;9;QH-2017-E KINH TẾ']
 ['16051728;Nguyễn Đức Bình;;F;6;QH-2016-E KTPT']
 ['16051726;Nguyễn Ngọc Diệp;10/10/1998;F;8;QH-2017-E KINH TẾ']
 ['16051725;Nguyễn Thị Ngọc Diệp;08/10/1998;F;7;QH-2017-E KTPT']
 ['16050018;Nguyễn Kim Dung;20/10/1998;F;7;QH-2016-E KTPT']
 ['16051729;Nguyễn Thị Dung;20/06/1998;F;6;QH-2017-E KTPT']
 ['16050020;Lâm Tuấn Đạt;20/01/1998;F;5;QH-2016-E KTPT']
 ['16050021;Lê Thị Giang;07/09/1998;M;;QH-2017-E KINH TẾ']
 ['16051730;Mai Thị Giang;08/09/1998;M;9;QH-2017-E KTPT']
 ['16052312;Lý Thị Tuyết Hằng;22/08/1998;F;;QH-2017-E KTPT']
 ['16050027;Lê Thị Hằng;10/08/1998;F;7;QH-2017-E KINH TẾ']
 ['16050028;Nguyễn Thị Thúy Hiền;12/03/1998;M;8;QH-2017-E KINH